# Generated by Django 3.2.7 on 2021-10-08 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
