# Generated by Django 3.2.7 on 2021-10-07 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemstatus',
            old_name='order_item_status_description',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_status_description',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_message',
            new_name='message',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='shippingitem',
            table='shipping_order_items',
        ),
    ]
