# Generated by Django 3.2.7 on 2021-10-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection_id',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
    ]
