# Generated by Django 3.2.7 on 2021-10-07 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211007_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scent',
            old_name='scent_description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='productscent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productscent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
